pipeline:
  # Building pushes to [dev] branch (nightly, latest-stable)
  # Repository must be trusted in Drone
  publish-nightly:
    when:
      event: push
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - yarn install
      - VERSION=$(/scripts/prepare_downstream)
      - /scripts/npm_patch_rc
      - /scripts/yarn_publish $VERSION nightly
    secrets: [ npm_repository, npm_token ]

branches: dev
