stages:
  - CI/CD
  - install
  - unit-tests
  - functional-tests
  - integration-tests
  - create-resolve-app-tests
  - clear

variables:
  GIT_STRATEGY: none

cache:
  untracked: true
  paths:
    - resolve-$CI_PIPELINE_ID
    - node_modules

prepare environment:
  stage: CI/CD
  tags:
    - ubuntu
  only:
    - ci/cd
  except:
    - triggers
  variables:
    GIT_STRATEGY: clone
  script:
    - yarn
    - pm2 delete trigger-on-pull-request || true
    - pm2 start trigger-on-pull-request/index.js --name trigger-on-pull-request

macOS (install):
  stage: install
  tags:
    - macos
  only:
    - triggers
  script:
    - echo CI_PIPELINE_TRIGGERED $CI_PIPELINE_TRIGGERED
    - echo TARGET_BRANCH_NAME $TARGET_BRANCH_NAME
    - rm -rf resolve-$CI_PIPELINE_ID || true
    - git clone https://github.com/reimagined/resolve.git resolve-$CI_PIPELINE_ID
    - cd resolve-$CI_PIPELINE_ID
    - git fetch origin $MERGE_COMMIT_SHA:merge-commit
    - git checkout merge-commit
    - yarn

ubuntu (install):
  stage: install
  tags:
    - ubuntu
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED
      - $TARGET_BRANCH_NAME == 'master'
  script:
    - rm -rf resolve-$CI_PIPELINE_ID || true
    - git clone https://github.com/reimagined/resolve.git resolve-$CI_PIPELINE_ID
    - cd resolve-$CI_PIPELINE_ID
    - git fetch origin $MERGE_COMMIT_SHA:merge-commit
    - git checkout merge-commit
    - yarn

eslint:
  stage: unit-tests
  tags:
    - any
  only:
    - triggers
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - yarn lint

prettier-check:
  stage: unit-tests
  tags:
    - any
  only:
    - triggers
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - if [ "$(node_modules/.bin/prettier --no-semi --single-quote --list-different "**/*.js")" ]; then exit 1; fi
    
unit-tests:
  stage: unit-tests
  tags:
    - any
  only:
    - triggers
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - yarn test

macOS (functional-tests):
  stage: functional-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - yarn test:functional safari
    
ubuntu (functional-tests):
  stage: functional-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - DISPLAY=:0 yarn test:functional chromium

bus:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(memory, rabbitmq, zeromq)"

storage:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(memory, mongodb, mysql, dynamodb)"
    
readmodel-adapter:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(memory, mongodb, mysql)"
    
subscribe-adapters:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(mqtt, socket.io)"
    
macOS (npx):
  stage: create-resolve-app-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo npx

ubuntu (npx):
  stage: create-resolve-app-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo npx

macOS (yarn):
  stage: create-resolve-app-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo yarn
    
ubuntu (yarn):
  stage: create-resolve-app-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo yarn

macOS (clear):
  stage: clear
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (clear):
  stage: clear
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu
