stages:
  - ci/cd
  - install
  - lint
  - unit-tests
  - functional-tests
  - integration-tests
  - create-resolve-app-tests
  - clear

ci/cd:
  stage: ci/cd
  tags:
    - ci/cd
  only:
    - ci/cd
  script:
    - echo ci/cd

macOS (install):
  stage: install
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (install):
  stage: install
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu

eslint:
  stage: lint
  only:
    - triggers
  script:
    - echo eslint
   
prettier-check:
  stage: lint
  only:
    - triggers
  script:
    - echo prettier-check
    
macOS (unit-tests):
  stage: unit-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (unit-tests):
  stage: unit-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu

macOS (functional-tests):
  stage: functional-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (functional-tests):
  stage: functional-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu

bus:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo (memory, rabbitmq, zeromq)

storage:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo (memory, mongodb, mysql, dynamodb)
    
readmodel-adapter:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo (memory, mongodb, mysql)         
    
subscribe-adapters:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo (mqtt, socket.io)
    
macOS (npx):
  stage: create-resolve-app-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo npx

ubuntu (npx):
  stage: create-resolve-app-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo npx

macOS (yarn):
  stage: create-resolve-app-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo yarn
    
ubuntu (yarn):
  stage: create-resolve-app-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo yarn

macOS (clear):
  stage: clear
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (clear):
  stage: clear
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu
