stages:
  - prepare-environment
  - start-environment
  - install
  - unit-tests
  - functional-tests
  - integration-tests
  - finish

variables:
  GIT_STRATEGY: none

cache:
  untracked: true
  paths:
    - resolve-$CI_PIPELINE_ID
    - ci-cd
    - .yarn-cache
  policy: pull

###############
# CI/CD setup #
###############

ubuntu (prepare environment):
  stage: prepare-environment
  tags:
    - ubuntu
  only:
    - ci/cd
  except:
    - triggers
  cache:
    policy: pull-push
  script:
    - rm -rf ci-cd || true
    - git clone https://github.com/reimagined/resolve.git ci-cd
    - cd ci-cd
    - git fetch origin ci/cd:ci/cd
    - git checkout ci/cd
    - yarn install --frozen-lockfile --cache-folder ../.yarn-cache

macOS (prepare environment):
  stage: prepare-environment
  tags:
    - macos
  only:
    - ci/cd
  except:
    - triggers
  cache:
    policy: pull-push
  script:
    - rm -rf ci-cd || true
    - git clone https://github.com/reimagined/resolve.git ci-cd
    - cd ci-cd
    - git fetch origin ci/cd:ci/cd
    - git checkout ci/cd
    - yarn install --frozen-lockfile --cache-folder ../.yarn-cache

ubuntu (start environment):
  stage: start-environment
  tags:
    - ubuntu
  only:
    - ci/cd
  except:
    - triggers
  cache:
    policy: pull
  script:
    - cd ci-cd
    - pm2 delete trigger-on-pull-request || true
    - pm2 start trigger-on-pull-request/index.js --name trigger-on-pull-request

##################################
# pull request -> dev or release #
##################################

install:
  stage: install
  tags:
    - macos
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME =~ /^feature\/.+/
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'dev'
      - $TARGET_BRANCH_NAME =~ /^release\/.+/
  cache:
    policy: pull-push
  before_script:
    - node ci-cd/create-github-status/index.js --state pending --context "1. Pipeline" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_PIPELINE_URL
  script:
    - rm -rf resolve-$CI_PIPELINE_ID || true
    - git clone https://github.com/reimagined/resolve.git resolve-$CI_PIPELINE_ID
    - cd resolve-$CI_PIPELINE_ID
    - git fetch origin $MERGE_COMMIT_SHA:merge-commit
    - git checkout merge-commit
    - yarn install --frozen-lockfile --cache-folder ../.yarn-cache

checks:
  stage: unit-tests
  tags:
    - macos
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME =~ /^feature\/.+/
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'dev'
      - $TARGET_BRANCH_NAME =~ /^release\/.+/
  cache:
    policy: pull
  before_script:
    - node ci-cd/job-status/index.js --start
    - node ci-cd/create-github-status/index.js --state pending --context "2. Unit tests" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_JOB_URL
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - if [ "$(node_modules/.bin/prettier --no-semi --single-quote --list-different "**/*.js")" ]; then exit 1; fi
    - npx npm-run-all -p test lint
    - cd ..
    - node ci-cd/job-status/index.js --end
  after_script:
    - if [ "$(node ci-cd/job-status/index.js --isSucceeded)" == "true" ]; then node ci-cd/create-github-status/index.js --state success --context "2. Unit tests" --description "Build ♯$CI_PIPELINE_IID succeeded in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; else node ci-cd/create-github-status/index.js --state failure --context "2. Unit tests" --description "Build ♯$CI_PIPELINE_IID failed in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; fi

functional-tests:
  stage: functional-tests
  tags:
    - macos
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME =~ /^feature\/.+/
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'dev'
      - $TARGET_BRANCH_NAME =~ /^release\/.+/
  cache:
    policy: pull
  before_script:
    - node ci-cd/job-status/index.js --start
    - node ci-cd/create-github-status/index.js --state pending --context "3. Functional tests" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_JOB_URL
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - if [ "$(node_modules/.bin/prettier --no-semi --single-quote --list-different "**/*.js")" ]; then exit 1; fi
    - yarn test:functional safari
    - cd ..
    - node ci-cd/job-status/index.js --end
  after_script:
    - if [ "$(node ci-cd/job-status/index.js --isSucceeded)" == "true" ]; then node ci-cd/create-github-status/index.js --state success --context "3. Functional tests" --description "Build ♯$CI_PIPELINE_IID succeeded in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; else node ci-cd/create-github-status/index.js --state failure --context "3. Functional tests" --description "Build ♯$CI_PIPELINE_IID failed in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; fi

#################
# dev -> master #
#################

macOS (install):
  stage: install
  tags:
    - macos
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  cache:
    policy: pull-push
  before_script:
    - node ci-cd/create-github-status/index.js --state pending --context "1. Pipeline" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_PIPELINE_URL
  script:
    - rm -rf resolve-$CI_PIPELINE_ID || true
    - git clone https://github.com/reimagined/resolve.git resolve-$CI_PIPELINE_ID
    - cd resolve-$CI_PIPELINE_ID
    - git fetch origin $MERGE_COMMIT_SHA:merge-commit
    - git checkout merge-commit
    - yarn install --frozen-lockfile --cache-folder ../.yarn-cache
    - yarn packages

ubuntu (install):
  stage: install
  tags:
    - ubuntu
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  cache:
    policy: pull-push
  before_script:
    - node ci-cd/create-github-status/index.js --state pending --context "1. Pipeline" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_PIPELINE_URL
  script:
    - rm -rf resolve-$CI_PIPELINE_ID || true
    - git clone https://github.com/reimagined/resolve.git resolve-$CI_PIPELINE_ID
    - cd resolve-$CI_PIPELINE_ID
    - git fetch origin $MERGE_COMMIT_SHA:merge-commit
    - git checkout merge-commit
    - yarn install --frozen-lockfile --cache-folder ../.yarn-cache
    - yarn packages

eslint + prettier:
  stage: unit-tests
  tags:
    - any
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  before_script:
    - node ci-cd/job-status/index.js --start
    - node ci-cd/create-github-status/index.js --state pending --context "2. ESLint + Prettier" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_JOB_URL
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - if [ "$(node_modules/.bin/prettier --no-semi --single-quote --list-different "**/*.js")" ]; then exit 1; fi
    - yarn lint
    - cd ..
    - node ci-cd/job-status/index.js --end
  after_script:
    - if [ "$(node ci-cd/job-status/index.js --isSucceeded)" == "true" ]; then node ci-cd/create-github-status/index.js --state success --context "2. ESLint + Prettier" --description "Build ♯$CI_PIPELINE_IID succeeded in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; else node ci-cd/create-github-status/index.js --state failure --context "2. ESLint + Prettier" --description "Build ♯$CI_PIPELINE_IID failed in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; fi

unit-tests:
  stage: unit-tests
  tags:
    - any
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  before_script:
    - node ci-cd/job-status/index.js --start
    - node ci-cd/create-github-status/index.js --state pending --context "3. Unit-tests" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_JOB_URL
  script:
    - cd resolve-$CI_PIPELINE_ID/
    - yarn test
    - cd ..
    - node ci-cd/job-status/index.js --end
  after_script:
    - if [ "$(node ci-cd/job-status/index.js --isSucceeded)" == "true" ]; then node ci-cd/create-github-status/index.js --state success --context "3. Unit-tests" --description "Build ♯$CI_PIPELINE_IID succeeded in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; else node ci-cd/create-github-status/index.js --state failure --context "3. Unit-tests" --description "Build ♯$CI_PIPELINE_IID failed in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; fi

macOS (create-resolve-app + functional-tests):
  stage: functional-tests
  tags:
    - macos
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  before_script:
    - node ci-cd/job-status/index.js --start
    - node ci-cd/create-github-status/index.js --state pending --context "4. Functional-tests (macOS)" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_JOB_URL
  script:
    - cd resolve-$CI_PIPELINE_ID
    - pm2 delete local-registry || true
    - pm2 start babel.compile.js --name local-registry -- --local-registry
    - cd ..
    - sleep 3
    - rm -rf hacker-news || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e hacker-news hacker-news
    - cd hacker-news
    - yarn test:functional safari
    - cd ..
    - rm -rf hacker-news
    - rm -rf hello-world || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e hello-world hello-world
    - cd hello-world
    - yarn test:functional safari
    - cd ..
    - rm -rf hello-world
    - rm -rf shopping-list-advanced || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e shopping-list-advanced shopping-list-advanced
    - cd shopping-list-advanced
    - yarn test:functional safari
    - cd ..
    - rm -rf shopping-list-advanced
    - rm -rf shopping-list || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e shopping-list shopping-list
    - cd shopping-list
    - yarn test:functional safari
    - cd ..
    - rm -rf shopping-list
    - rm -rf with-postcss || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e with-postcss with-postcss
    - cd with-postcss
    - yarn test:functional safari
    - cd ..
    - rm -rf with-postcss
    - rm -rf with-saga || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e with-saga with-saga
    - cd with-saga
    - yarn test:functional safari
    - cd ..
    - rm -rf with-saga
    - rm -rf with-styled-components || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e with-styled-components with-styled-components
    - cd with-styled-components
    - yarn test:functional safari
    - cd ..
    - rm -rf with-styled-components
    - node ci-cd/job-status/index.js --end
  after_script:
    - if [ "$(node ci-cd/job-status/index.js --isSucceeded)" == "true" ]; then node ci-cd/create-github-status/index.js --state success --context "4. Functional-tests (macOS)" --description "Build ♯$CI_PIPELINE_IID succeeded in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; else node ci-cd/create-github-status/index.js --state failure --context "4. Functional-tests (macOS)" --description "Build ♯$CI_PIPELINE_IID failed in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; fi
    
ubuntu (create-resolve-app + functional-tests):
  stage: functional-tests
  tags:
    - ubuntu
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  before_script:
    - node ci-cd/job-status/index.js --start
    - node ci-cd/create-github-status/index.js --state pending --context "5. Functional-tests (Ubuntu)" --description "Waiting ♯$CI_PIPELINE_IID for status to be reported" --targetUrl $CI_JOB_URL
  script:
    - cd resolve-$CI_PIPELINE_ID
    - pm2 delete local-registry || true
    - pm2 start babel.compile.js --name local-registry -- --local-registry
    - cd ..
    - sleep 3
    - export DISPLAY=:0
    - rm -rf hacker-news || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e hacker-news hacker-news
    - cd hacker-news
    - yarn test:functional chromium
    - cd ..
    - rm -rf hacker-news
    - rm -rf hello-world || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e hello-world hello-world
    - cd hello-world
    - yarn test:functional chromium
    - cd ..
    - rm -rf hello-world
    - rm -rf shopping-list-advanced || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e shopping-list-advanced shopping-list-advanced
    - cd shopping-list-advanced
    - yarn test:functional chromium
    - cd ..
    - rm -rf shopping-list-advanced
    - rm -rf shopping-list || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e shopping-list shopping-list
    - cd shopping-list
    - yarn test:functional chromium
    - cd ..
    - rm -rf shopping-list
    - rm -rf with-postcss || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e with-postcss with-postcss
    - cd with-postcss
    - yarn test:functional chromium
    - cd ..
    - rm -rf with-postcss
    - rm -rf with-saga || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e with-saga with-saga
    - cd with-saga
    - yarn test:functional chromium
    - cd ..
    - rm -rf with-saga
    - rm -rf with-styled-components || true
    - node resolve-$CI_PIPELINE_ID/packages/core/create-resolve-app/bin/index.js --local-registry -c $MERGE_COMMIT_SHA -e with-styled-components with-styled-components
    - cd with-styled-components
    - yarn test:functional chromium
    - cd ..
    - rm -rf with-styled-components
    - node ci-cd/job-status/index.js --end
  after_script:
    - if [ "$(node ci-cd/job-status/index.js --isSucceeded)" == "true" ]; then node ci-cd/create-github-status/index.js --state success --context "5. Functional-tests (Ubuntu)" --description "Build ♯$CI_PIPELINE_IID succeeded in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; else node ci-cd/create-github-status/index.js --state failure --context "5. Functional-tests (Ubuntu)" --description "Build ♯$CI_PIPELINE_IID failed in $(cat ci-cd/job.time)" --targetUrl $CI_JOB_URL; fi

ubuntu (integration-tests):
  stage: integration-tests
  tags:
    - ubuntu
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  only:
    variables:
      - $SOURCE_BRANCH_NAME == 'dev'
  only:
    variables:
      - $TARGET_BRANCH_NAME == 'master'
  script:
    - echo "integration-tests"

##########
# finish #
##########

success:
  stage: finish
  when: on_success
  tags:
    - any
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  cache:
    policy: pull
  script:
    - rm -rf resolve-$CI_PIPELINE_ID
    - node ci-cd/create-github-status/index.js --state success --context "1. Pipeline" --description "Build ♯$CI_PIPELINE_IID succeeded" --targetUrl $CI_PIPELINE_URL

failure:
  stage: finish
  when: on_failure
  tags:
    - any
  only:
    variables:
      - $CI_PIPELINE_TRIGGERED == 'true'
  cache:
    policy: pull
  script:
    - node ci-cd/create-github-status/index.js --state failure --context "1. Pipeline" --description "Build ♯$CI_PIPELINE_IID failed" --targetUrl $CI_PIPELINE_URL
