stages:
  - CI/CD
  - install
  - lint
  - unit-tests
  - functional-tests
  - integration-tests
  - create-resolve-app-tests
  - clear

prepare environment:
  stage: CI/CD
  tags:
    - ubuntu
  only:
    - ci/cd
  script:
    - yarn
    - pm2 delete trigger-on-pull-request || true
    - pm2 start trigger-on-pull-request/index.js --name trigger-on-pull-request -- --githubToken $GITHUB_RESOLVE_TOKEN --gitlabUrl $GITLAB_PIPELINE_URL --gitlabToken $GITLAB_PIPELINE_TOKEN

macOS (install):
  stage: install
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (install):
  stage: install
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu

eslint:
  stage: lint
  tags:
    - macos
  only:
    - triggers
  script:
    - echo eslint
   
prettier-check:
  stage: lint
  tags:
    - macos
  only:
    - triggers
  script:
    - echo prettier-check
    
macOS (unit-tests):
  stage: unit-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (unit-tests):
  stage: unit-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu

macOS (functional-tests):
  stage: functional-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (functional-tests):
  stage: functional-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu

bus:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(memory, rabbitmq, zeromq)"

storage:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(memory, mongodb, mysql, dynamodb)"
    
readmodel-adapter:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(memory, mongodb, mysql)"
    
subscribe-adapters:
  stage: integration-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo "(mqtt, socket.io)"
    
macOS (npx):
  stage: create-resolve-app-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo npx

ubuntu (npx):
  stage: create-resolve-app-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo npx

macOS (yarn):
  stage: create-resolve-app-tests
  tags:
    - macos
  only:
    - triggers
  script:
    - echo yarn
    
ubuntu (yarn):
  stage: create-resolve-app-tests
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo yarn

macOS (clear):
  stage: clear
  tags:
    - macos
  only:
    - triggers
  script:
    - echo macos
    
ubuntu (clear):
  stage: clear
  tags:
    - ubuntu
  only:
    - triggers
  script:
    - echo ubuntu
